# Generated by Django 5.2.4 on 2025-08-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
